version: '3.5'

services:
  info-mongo:
    build:
      context: .
      dockerfile: Dockerfile.mongo
    ports:
      - '27019:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=info
    volumes:
      - mongo-volume:/data/db

volumes:
  mongo-volume: {}
